/* SPDX-License-Identifier: LGPL-2.1-or-later */
/* Generated by Bazel build - do not edit manually */

#pragma once

#include <stdint.h>

/* Version information */
#define PROJECT_VERSION @PROJECT_VERSION@
#define PROJECT_VERSION_STR "@PROJECT_VERSION_STR@"
#define PROJECT_VERSION_FULL "@PROJECT_VERSION_FULL@"
#define PROJECT_URL "@PROJECT_URL@"
#define VERSION_TAG "@VERSION_TAG@"

/* Installation paths */
#define PREFIX "@PREFIX@"
#define PREFIX_NOSLASH "@PREFIX_NOSLASH@"
#define BINDIR "@BINDIR@"
#define LIBDIR "@LIBDIR@"
#define LIBEXECDIR "@LIBEXECDIR@"
#define SYSCONF_DIR "@SYSCONFDIR@"
#define INCLUDE_DIR "@INCLUDEDIR@"

/* Package directories */
#define PKGSYSCONFDIR "@PKGSYSCONFDIR@"
#define SYSTEMD_CATALOG_DIR "@CATALOGDIR@"
#define SYSTEM_DATA_UNIT_DIR "@SYSTEMUNITDIR@"
#define USER_DATA_UNIT_DIR "@USERUNITDIR@"
#define SYSTEM_PRESET_DIR "@SYSTEMPRESETDIR@"
#define USER_PRESET_DIR "@USERPRESETDIR@"
#define TMPFILES_DIR "@TMPFILESDIR@"
#define SYSUSERS_DIR "@SYSUSERSDIR@"
#define SYSCTL_DIR "@SYSCTLDIR@"
#define BINFMT_DIR "@BINFMTDIR@"
#define MODULESLOAD_DIR "@MODULESLOADDIR@"
#define UDEVLIBEXECDIR "@UDEVLIBEXECDIR@"
#define UDEV_RULES_DIR "@UDEVRULESDIR@"
#define UDEV_HWDB_DIR "@UDEVHWDBDIR@"
#define ENVIRONMENT_DIR "@ENVIRONMENTDIR@"
#define MODPROBE_DIR "@MODPROBEDIR@"
#define KERNEL_INSTALL_DIR "@KERNELINSTALLDIR@"
#define BOOTLIBDIR "@BOOTLIBDIR@"
#define POLKIT_RULES_DIR "@POLKITRULESDIR@"

/* Generator directories */
#define SYSTEM_GENERATOR_DIR "@LIBEXECDIR@/system-generators"
#define USER_GENERATOR_DIR "@LIBEXECDIR@/user-generators"
#define SYSTEM_ENV_GENERATOR_DIR "@LIBEXECDIR@/system-environment-generators"
#define USER_ENV_GENERATOR_DIR "@LIBEXECDIR@/user-environment-generators"

/* Configuration directories */
#define SYSTEM_CONFIG_UNIT_DIR "@PKGSYSCONFDIR@/system"
#define USER_CONFIG_UNIT_DIR "@PKGSYSCONFDIR@/user"

/* Other paths */
#define SYSTEM_SHUTDOWN_PATH "@LIBEXECDIR@/system-shutdown"
#define SYSTEM_SLEEP_PATH "@LIBEXECDIR@/system-sleep"

/* Binary paths */
#define SYSTEMCTL_BINARY_PATH "@SYSTEMCTL_BINARY_PATH@"
#define SYSTEMD_BINARY_PATH "@SYSTEMD_BINARY_PATH@"
#define SYSTEMD_EXECUTOR_BINARY_PATH "@SYSTEMD_EXECUTOR_BINARY_PATH@"
#define SYSTEMD_SHUTDOWN_BINARY_PATH "@SYSTEMD_SHUTDOWN_BINARY_PATH@"
#define SYSTEMD_CRYPTSETUP_PATH "@BINDIR@/systemd-cryptsetup"
#define SYSTEMD_FSCK_PATH "@LIBEXECDIR@/systemd-fsck"
#define SYSTEMD_GROWFS_PATH "@LIBEXECDIR@/systemd-growfs"
#define SYSTEMD_MAKEFS_PATH "@LIBEXECDIR@/systemd-makefs"
#define SYSTEMD_HOMEWORK_PATH "@LIBEXECDIR@/systemd-homework"
#define SYSTEMD_IMPORT_PATH "@LIBEXECDIR@/systemd-import"
#define SYSTEMD_IMPORT_FS_PATH "@LIBEXECDIR@/systemd-import-fs"
#define SYSTEMD_EXPORT_PATH "@LIBEXECDIR@/systemd-export"
#define SYSTEMD_PULL_PATH "@LIBEXECDIR@/systemd-pull"
#define SYSTEMD_SYSUPDATE_PATH "@LIBEXECDIR@/systemd-sysupdate"
#define SYSTEMD_INTEGRITYSETUP_PATH "@LIBEXECDIR@/systemd-integritysetup"
#define SYSTEMD_VERITYSETUP_PATH "@LIBEXECDIR@/systemd-veritysetup"
#define SYSTEMD_USERWORK_PATH "@LIBEXECDIR@/systemd-userwork"
#define SYSTEMD_MOUNTWORK_PATH "@LIBEXECDIR@/systemd-mountwork"
#define SYSTEMD_NSRESOURCEWORK_PATH "@LIBEXECDIR@/systemd-nsresourcework"
#define SYSTEMD_TTY_ASK_PASSWORD_AGENT_BINARY_PATH "@BINDIR@/systemd-tty-ask-password-agent"
#define SYSTEMD_UPDATE_HELPER_PATH "@LIBEXECDIR@/systemd-update-helper"
#define POLKIT_AGENT_BINARY_PATH "@BINDIR@/pkttyagent"

/* Data paths */
#define SYSTEMD_KBD_MODEL_MAP "@DATADIR@/systemd/kbd-model-map"
#define SYSTEMD_LANGUAGE_FALLBACK_MAP "@DATADIR@/systemd/language-fallback-map"
#define DOCUMENT_ROOT "@DATADIR@/systemd/gatewayd"

/* State paths */
#define RANDOM_SEED "@RANDOM_SEED@"
#define RANDOM_SEED_DIR "@RANDOM_SEED_DIR@"
#define CATALOG_DATABASE "@CATALOG_DATABASE@"
#define CERTIFICATE_ROOT "@CERTIFICATE_ROOT@"
#define DOC_DIR "@DATADIR@/doc/systemd"
#define SYSTEMD_TEST_DATA "@LIBEXECDIR@/tests/testdata"

/* Keyring paths */
#define USER_KEYRING_PATH "@PKGSYSCONFDIR@/import-pubring.pgp"
#define USER_KEYRING_PATH_LEGACY "@PKGSYSCONFDIR@/import-pubring.gpg"
#define VENDOR_KEYRING_PATH "@LIBEXECDIR@/import-pubring.pgp"

/* Defaults */
#define DEFAULT_TIMEOUT_SEC @DEFAULT_TIMEOUT_SEC@
#define DEFAULT_USER_TIMEOUT_SEC @DEFAULT_USER_TIMEOUT_SEC@
#define UPDATE_HELPER_USER_TIMEOUT_SEC @UPDATE_HELPER_USER_TIMEOUT_SEC@
#define HIGH_RLIMIT_NOFILE @HIGH_RLIMIT_NOFILE@
#define TTY_MODE 0600
#define TTY_GID 5
#define FALLBACK_HOSTNAME "localhost"
#define SYSTEMD_DEFAULT_LOCALE "C.UTF-8"
#define DEFAULT_USER_SHELL "/bin/bash"
#define DEFAULT_USER_SHELL_NAME "bash"
#define NOBODY_USER_NAME "nobody"
#define NOBODY_GROUP_NAME "nobody"
#define NOLOGIN "/usr/bin/nologin"

/* UID/GID ranges */
#define SYSTEM_ALLOC_UID_MIN 1
#define SYSTEM_UID_MAX 999
#define SYSTEM_ALLOC_GID_MIN 1
#define SYSTEM_GID_MAX 999
#define GREETER_UID_MIN 60578
#define GREETER_UID_MAX 60705
#define DYNAMIC_UID_MIN 61184
#define DYNAMIC_UID_MAX 65519
#define CONTAINER_UID_BASE_MIN 0x00080000
#define CONTAINER_UID_BASE_MAX 0x6FFF0000
#define FOREIGN_UID_BASE 0x7FFE0000

#define JOURNAL_STORAGE_DEFAULT STORAGE_AUTO
#define JOURNAL_STORAGE_DEFAULT_VAL STORAGE_AUTO
#define STATUS_UNIT_FORMAT_DEFAULT STATUS_UNIT_FORMAT_DESCRIPTION
#define STATUS_UNIT_FORMAT_DEFAULT_STR "description"
#define ANSI_OK_COLOR ANSI_HIGHLIGHT_GREEN
#define MEMORY_ACCOUNTING_DEFAULT 1

/* Build configuration */
#define BUILD_MODE_DEVELOPER 0
#define LOG_MESSAGE_VERIFICATION 0
#define FUZZ_USE_SIZE_LIMIT 0
#define SD_BOOT 0
#define RELATIVE_SOURCE_PATH "src"
#define SYSTEMD_SLOW_TESTS_DEFAULT 0

/* Network naming scheme */
#define EXTRA_NET_NAMING_SCHEMES
#define EXTRA_NET_NAMING_MAP
#define DEFAULT_NET_NAMING_SCHEME "latest"

/* External binary paths */
#define KEXEC "/usr/bin/kexec"
#define QUOTACHECK "/usr/bin/quotacheck"
#define KMOD "/usr/bin/kmod"
#define SULOGIN "/usr/bin/sulogin"
#define SWAPON "/usr/bin/swapon"
#define SWAPOFF "/usr/bin/swapoff"
#define AGETTY "/usr/bin/agetty"
#define MOUNT_PATH "/usr/bin/mount"
#define UMOUNT_PATH "/usr/bin/umount"
#define KBD_LOADKEYS "/usr/bin/loadkeys"
#define KBD_SETFONT "/usr/bin/setfont"

/* Enabled features - defaults for Bazel build */
#define HAVE_SPLIT_BIN 0
#define ENABLE_URLIFY 1
#define ENABLE_FEXECVE 1
#define ENABLE_FIRST_BOOT_FULL_PRESET 1
#define CREATE_LOG_DIRS 1
#define BUMP_PROC_SYS_FS_FILE_MAX 1
#define BUMP_PROC_SYS_FS_NR_OPEN 1

/* System features - always available on Linux */
#define HAVE_KEYCTL 0
#define HAVE_ADD_KEY 0
#define HAVE_REQUEST_KEY 0

/* key_serial_t for keyctl - may not be defined in all kernel headers */
#ifndef __kernel_key_t_defined
typedef int32_t key_serial_t;
#define __kernel_key_t_defined
#endif

#define HAVE_LINUX_BTRFS_H 1
#define HAVE_LINUX_MEMFD_H 1
#define HAVE_LINUX_VM_SOCKETS_H 1
#define HAVE_LINUX_TIME_TYPES_H 1
#define HAVE_SYS_AUXV_H 1
#define HAVE_IFADDRS_H 1
#define HAVE_MALLINFO 1
#define HAVE_MALLINFO2 1
#define HAVE_SECURE_GETENV 1
#define HAVE___SECURE_GETENV 0
#define HAVE_PIDFD_OPEN 1
#define HAVE_PIDFD_SEND_SIGNAL 1
#define HAVE_RT_SIGQUEUEINFO 1
#define HAVE_CLOSE_RANGE 1
#define HAVE_EPOLL_PWAIT2 1
#define HAVE_MOUNT_SETATTR 1
#define HAVE_MOVE_MOUNT 1
#define HAVE_OPEN_TREE 1
#define HAVE_MEMFD_CREATE 1
#define HAVE_COPY_FILE_RANGE 1
#define HAVE_EXPLICIT_BZERO 1
#define HAVE_REALLOCARRAY 1
#define HAVE_GETRANDOM 1
#define HAVE_GETTID 1
#define HAVE_NAME_TO_HANDLE_AT 1
#define HAVE_STRUCT_STATX 1
#define HAVE_SET_MEMPOLICY_HOME_NODE 1

/* Compiler features */
#define HAVE_GENERIC 1
#define HAVE_TYPEOF 1

/* gperf compatibility - use size_t for string length parameter */
#define GPERF_LEN_TYPE size_t

/* Type sizes for format-util.h - assuming x86_64 Linux */
#define SIZEOF_TIME_T 8
#define SIZEOF_TIMEX_MEMBER 8
#define SIZEOF_RLIM_T 8
#define SIZEOF_DEV_T 8
#define SIZEOF_INO_T 8
#define SIZEOF_PID_T 4
#define SIZEOF_UID_T 4
#define SIZEOF_GID_T 4

/* LONG_MAX as a string for sysctl */
#define LONG_MAX_STR "9223372036854775807"

/* Clock limits */
#define TIME_EPOCH 0
#define CLOCK_VALID_RANGE_USEC_MAX 0
#define DEFAULT_MANAGER_START_TIMEOUT_USEC 0

/* Compression default - COMPRESSION_NONE since no compression libs are enabled */
#define DEFAULT_COMPRESSION COMPRESSION_NONE

/* Optional library features - disabled by default */
#define HAVE_SECCOMP 0
#define HAVE_SELINUX 0
#define HAVE_APPARMOR 0
#define HAVE_SMACK 0
#define HAVE_AUDIT 0
#define HAVE_ACL 0
#define HAVE_LZ4 0
#define HAVE_XZ 0
#define HAVE_ZSTD 0
#define HAVE_BZIP2 0
#define HAVE_COMPRESSION 0
#define HAVE_GCRYPT 0
#define HAVE_OPENSSL 0
#define HAVE_QRENCODE 0
#define HAVE_MICROHTTPD 0
#define HAVE_GNUTLS 0
#define HAVE_LIBCURL 0
#define HAVE_LIBIDN 0
#define HAVE_LIBIDN2 0
#define HAVE_LIBIPTC 0
#define HAVE_PCRE2 0
#define HAVE_ELFUTILS 0
#define HAVE_LIBCRYPTSETUP 0
#define HAVE_LIBCRYPTSETUP_PLUGINS 0
#define HAVE_P11KIT 0
#define HAVE_LIBFIDO2 0
#define HAVE_TPM2 0
#define HAVE_PWQUALITY 0
#define HAVE_PASSWDQC 0
#define HAVE_DBUS 0
#define HAVE_PAM 0
#define HAVE_XKBCOMMON 0

/* Required libraries - enabled */
#define HAVE_BLKID 1
#define HAVE_LIBMOUNT 1
#define HAVE_KMOD 1
#define HAVE_LIBCAP 0
#define HAVE_LIBFDISK 0

/* BPF */
#define BPF_FRAMEWORK 0
#define HAVE_LIBBPF 0

/* SSH */
#define LINK_SSH_PROXY_DROPIN 0
#define LINK_SSHD_USERDB_DROPIN 0
#define CREATE_SSHDPRIVSEPDIR 0
#define SSHDPRIVSEPDIR "/run/sshd"

/* Shell integration */
#define LINK_SHELL_EXTRA_DROPIN 0
#define LINK_OSC_CONTEXT_DROPIN 0
#define SHELLPROFILEDIR "/etc/profile.d"

/* Feature enables - match HAVE_* flags */
#define ENABLE_SMACK 0
#define ENABLE_SELINUX 0
#define ENABLE_APPARMOR 0
#define ENABLE_AUDIT 0
#define ENABLE_IMA 0
#define ENABLE_TOMOYO 0
#define ENABLE_SECCOMP 0

/* EFI support - disabled for now */
#define ENABLE_EFI 0
#define HAVE_GNU_EFI 0
