# SPDX-License-Identifier: LGPL-2.1-or-later

"""BUILD file for busctl."""

load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "busctl",
    srcs = [
        "busctl.c",
        "busctl-introspect.c",
        "busctl-introspect.h",
        "//src/version:version_h",
    ],
    copts = [
        "-include", "$(GENDIR)/bazel/config.h",
        "-I$(GENDIR)/src/version",
    ],
    deps = [
        "//bazel:config",
        "//src/shared:shared_static",
    ],
)
